export const CREATE_TODO = 'CREATE_TODO';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
